routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function()
{
    //Slug routes
    Route::resource('slugs', 'SlugController');
});

app/Slug.php
<?php
/**
 * Slug Model
 * 
 * @created    29/09/2018
 * @package    Ak Clinics
 * @copyright  Copyright (C) 2018
 * @license    Proprietary
 * @author     Mohit Thakur
 */
namespace App;
use Kyslik\ColumnSortable\Sortable;
use Illuminate\Database\Eloquent\SoftDeletes;

class Slug extends AppModel
{
	use Sortable,SoftDeletes;
	/**
     * The table associated with the model.
     *
     * @var string
     */
//    protected $table = 'slugs';
	
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name','is_active'];
	
	/**
	* The attributes that should be mutated to deleted_at.
	*
	* @var array
	*/
    protected $deleted_at = ['deleted_at'];
}

app/Http/Controllers/SlugController.php
<?php
/**
 * Slug Controller
 * 
 * @created    29/09/2018
 * @package    Ak Clinics
 * @copyright  Copyright (C) 2018
 * @license    Proprietary
 * @author     Mohit Thakur
 */

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Input;

use App\Slug;
use DB;

class SlugController extends AppController
{
	// Set for public Model name
	public $modelName = "Slug";
	
	//Define validation rules for the request
	public $rules = array(
        'name' => 'required'
    );
	
	/**
	* Display a listing of the resource.
	*
	* @return \Illuminate\Http\Response
	*/
    public function index()
    {
		$conditions = $this->getSearchConditions([
            ["view_field" => "name", "type" => "string"],
        ]);
		
		if($conditions)
		{
			//Paginate page according to search filter
			$records = Slug::sortable()->whereRaw($conditions)->paginate(PAGINATION_LIMIT);
		}
		else 
		{
			//Paginate page without search filter
			$records = Slug::sortable()->paginate(PAGINATION_LIMIT);
		}
        
        return view('admin.slug.index', ['records' => $records]);
	}
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //Return Project Add form
		return view('admin.slug.form');
    }
	
	/**
	* Adds new record
	* @return type
	*/
    public function store($route = NULL)
    {
        //rote set for redirect the after save slugs summary
		$route = "admin/slugs";
		//Call parent method for add the Contact details
		return parent::add_record($route);
	}
    
    
    /**
    * Show the form for editing the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function edit($id)
    {
		//Get a records in projects table
		$slug = Slug::findOrFail($id);
		//Set id and records to view
		return view('admin.slug.form', compact("id", "slug"));
    }
    
    /**
	* Update the specified resource in storage.
	* @param Slug $slug
	* @return type
	*/
    public function update(Slug $slug, $route = NULL)
    {
        //rote set for redirect the after save slugs summary
        $route = "admin/slugs";
		//Call parent method foe update the slug details
		return parent::edit_record($slug, $route);
	}
    
    /**
	* Deletes record
	* @param Contact $contact
	* @return type
	*/
    public function destroy(Slug $slug)
    {
		//Destroy function call the show method
    }
    
    /**
	* Show the form for editing the specified resource.
	*
	* @param  int  $id
	* @return \Illuminate\Http\Response
	*/
    public function show(Slug $slug)
    {
        //rote set for redirect the after save slugs summary
        $route = "admin/slugs";

        //Call a destroy action in main controller to delete a record soft delete
        return parent::delete_record($slug, $route);
    }
    
    /**
     * Status update Existing Record
     * @param type $id , $status
     */
    public function admin_toggleStatus(Slug $slug, $is_active) 
	{
        //rote set for redirect the after save slugs summary
        $route = "admin/slugs";

        //Call a destroy action in main controller to delete a record soft delete
        return parent::toggleStatus($slug, $is_active, $route);
    }
}

resources/views/admin/slug/form.blade.php
<?php
/**
 * Slug Add/Edit Form 
 * 
 * @created    10/01/2018
 * @package    AK Clinics
 * @copyright  Copyright (C) 2018
 * @author     Mohit Thakur
 */
?>
@extends('layouts.admin')
@section('content')

<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="">Home</a>
        </li>
        <li>
            <span>Slug</span>
        </li>
        <li>
            <span>Add</span>
        </li>
    </ul>
</div>
<div class="clearfix"></div>
@include('../partials/message')
<div class="form__structure">
    @if(isset($slug))
    {{ Form::model($slug, array('route' => array('slugs.update', $slug->id), 'class' => 'form-horizontal form-row-seperated', 'method' => 'PUT')) }}
    @else
    {!! Form::open(array('url' => 'admin/slugs', 'class' => 'form-horizontal form-row-seperated')) !!}
    @endif	
    {{ csrf_field() }}
    {{ Form::hidden('is_active', '1') }}
    <div class="form-body">
        <div class="form-group">
            {!! Form::label('Slug Name', 'Slug Name', array('class' => 'control-label col-md-4 col-sm-4 col-xs-12')) !!}
            <div class="col-md-6 col-sm-6 col-xs-12">
                {!! Form::text('name', null, array('class' => 'form-control', 'placeholder' => 'Slug Name', 'required' => 'required')) !!}
                <!--<input type="text" name="name" />-->
                @if ($errors->has('name'))
                <span class="help-block">
                    {{ $errors->first('name') }}
                </span>
                @endif
            </div>
        </div>
        <div class="action-buttons">
            <div class="col-md-8 col-sm-8 col-xs-12 col-md-offset-4 col-sm-offset-4 col-xs-offset-0">
                <button type="submit" class="btn blue">Submit</button>
                <!--{!! Form::submit('Submit', array('class' => 'btn blue')) !!}-->
                <button type="reset" class="btn grey">Cancel</button>
            </div> 
        </div>
    </div>
    {!! Form::close() !!}
</div>
@stop

resources/views/admin/slug/index.blade.php
<?php 
/**
 * Slug Index View - Shows Slug summary for Admin users
 * 
 * @created    10/01/2018
 * @package    AK Clinics
 * @copyright  Copyright (C) 2018
 * @author     Mohit Thakur
 */
?>
@extends('layouts.admin')
@section('content')
<!-- BEGIN PAGE BAR -->
<div class="page-bar">
	<ul class="page-breadcrumb">
		<li>
			<i class="fa fa-home"></i>
			<a href="index.html">Home</a>
		</li>
		<li>
			<span>Slug</span>
		</li>
		<li>
			<span>Summary</span>
		</li>
	</ul>
</div>
<!-- END PAGE BAR -->

<!-- END PAGE HEADER-->
<!-- BEGIN DASHBOARD STATS 1-->

<div class="clearfix"></div>
@include('../partials/message')
<!-- END DASHBOARD STATS 1-->
<div class="data__filter">
	<div class="form__structure shadow">
		<form class="form-horizontal form-row-seperated">
			<div class="row">
				<div class="col-md-12 col-xs-12">
					<div class="row">
						<div class="col-md-6 col-sm-6 col-xs-12">
							<div class="form-group">
								{!! Form::label('name', 'Slug Name', array('class' => 'control-label col-md-4 col-sm-4 col-xs-12')) !!}
								<div class="col-md-6 col-sm-6 col-xs-12">
									{!! Form::text('name', '', array('class' => 'form-control', 'placeholder' => 'Slug Name')) !!}
								</div>
							</div>
						</div>
					</div>
					<div class="action-buttons text-center">
						<div class="col-md-12 col-sm-12 col-xs-12">
							<button type="submit" href="javascript:;" class="btn blue">Submit</button>
							<a href="{{ route('slugs.index') }}" class="btn default">Clear</a>
						</div> 
					</div>
				</div>
			</div>
		</form>
	</div>
</div>
<div class="table__structure">
	<div class="table__counters">
		Page {{ $records->currentPage() }} of {{ $records->lastPage() }} showing {{ $records->count() }} records out of {{ $records->total() }} total
	</div>
	<div class="table-responsive">
		<table class="table table-striped table-bordered table-checkable order-column" id="sample_1_2">
			<thead>
				<tr>
					<th> SR No. </th>
					<th> Slug Name </th>
					<th> Actions </th>
				</tr>
			</thead>
			<tbody>
				<?php $i = 1; ?>
				@foreach ($records as $record)
				<tr class="odd gradeX">
					<td> {{ $i++ }} </td>
					<td> {{ $record->name }} </td>
					<td>
						<a href="{{ route('slugs.edit', $record->id) }}" title="Edit" class="icon currency-color">
							<i class=" fa fa-edit"></i>
						</a>

						<a href="{{ route('slugs.destroy', $record->id) }}" title="Delete" class="icon lightBlue-color">
							<i class=" fa fa-trash"></i>
						</a>
					</td>
				</tr>
				@endforeach
			</tbody>
		</table>
	</div>
	<nav aria-label="Page navigation">
		<ul class="pagination">
			{{ $records->links() }}
		</ul>
	</nav>
</div>
@stop